### ISSUE TITLE
目录可切换为学校样例格式的提议

### ISSUE THREAD

**Issue by BluesCas** [nanmu42/CQUThesis#12]
The CQU-provided .doc template gives an example of ToC with section styled in \zihao{5}\heiti and subsection styled in \zihao{5}\songti.

It is expected that some users may want to stick to this instruction.

A feasible alteration can be achieved by adding the following lines as an alternative to cquthesis.sty.

**\renewcommand{\cftsecfont}{\heiti\zihao{5}}
\renewcommand{\cftsubsecfont}{\zihao{5}}**

**Comment by BluesCas** [comment]
进行上述修改后，正文里的各级标题都会出现字号异常，可以在main.tex文件中 \mainmatter的前面或后面写入下面两行命令进行强行修正

**\titleformat*{\section}{\zihao{-3}\heiti}
\titleformat*{\subsection}{\zihao{4}\heiti}**

建议更新时也按此法修改main.tex

**Comment by BluesCas** [comment]
Hi dude

建议将以下意思以注释的表达进cover.tex的摘要部分，in case some may want to strictly stick to the as-provided school template

**%如果要达到doc模版里要求的摘要正文与关键词空两行的效果，可以在摘要正文后面打个\\增加空行**

**Comment by nanmu42** [comment]
你好！欢迎使用CQUThesis！

请[下载这个branch](https://github.com/nanmu42/CQUThesis/archive/seriftoc.zip)协助测试，请在`main.tex`中开启`seriftoc`选项。
我这边还没有观察到“正文里的各级标题都会出现字号异常”的问题，请在测试中留意下。

这个问题预计会在#13 中解决。

感谢支持CQUThesis！

**Comment by BluesCas** [comment]
Hi dude

Many thanks for your instant reply.

The referred branch is tested, while it appears that titles in the main matter will go false-formatted when type-setting with Tex Live for Mac using this branch.

Following lines added closely before or after **\mainmatter** in "main.tex" may fix this and hopefully without causing other problems in other Tex typesetters.

**\titleformat*{\section}{\zihao{-3}\heiti}
\titleformat*{\subsection}{\zihao{4}\heiti}**

_(They require a package "titlesec", which is already planted in CQUthesis.)_

**Comment by BluesCas** [comment]
sorry dude!

This branch works very well, the problem above is due to my mistake.

For avoidance of misunderstanding, I'd like to make following clearance:
1. titlesec.pkg is not originally included in CQUthesis.
2. I introduced this into my piece and forgot it.
3. It is this package that caused this problem (it is in controversy with tocloft)

Many thanks again.

**Comment by nanmu42** [comment]
很高兴能解决你的问题。
#13 已经和master合并。

祝你使用愉快！
