### ISSUE TITLE
图和表的中英双语题注

### ISSUE THREAD

**Issue by craneaow** [nanmu42/CQUThesis#20]
能不能加入图标的双语标题？
当前，用\ccaptain，报错
用\bicaptain,中文标题：“图xx”，但是英文标题也是“图xx”。

**Comment by nanmu42** [comment]
你好，我刚刚结束旅行，这件事已加入日程。
这是一个很棒的建议，谢谢你。

craneaow notifications@github.com 於 2016年7月5日週二 12:45 寫道：

**Comment by nanmu42** [comment]
你好！欢迎使用CQUThesis！

CQUThesis的master分支已经进行了相关更新，希望能够满足您的需求。
请参阅最新的[用户文档](https://github.com/nanmu42/CQUThesis/raw/master/cquthesis.pdf)的**3.9.1节**和示例文件以了解用法，详情请参阅 #21 。

在确认您的问题得到解决后，请关闭这个Issue。

祝你使用愉快！
