### ISSUE TITLE
重庆大学开源镜像站添加 CTAN 源了

### ISSUE THREAD

**Issue by rhiswell** [nanmu42/CQUThesis#28]
https://mirrors.cqu.edu.cn/ctan

https://www.ctan.org/pkg/cquthesis => https://mirrors.cqu.edu.cn/ctan/macros/latex/contrib/cquthesis/

**Comment by nanmu42** [comment]
感谢通知！！
简直不要太开心！！！！

**Comment by nanmu42** [comment]
@rhiswell 能联系上镜像相关负责人否？到[CTAN镜像登记](http://ctan.org/mirrors/register/)去做个注册？这样CTAN以及各个发行版可以自动连接到重大镜像这边，不需要用户手动设置。
谢谢。

**Comment by rhiswell** [comment]
@nanmu42 今天内会有小伙伴完成这件事情

**Comment by nanmu42** [comment]
@rhiswell 棒！

**Comment by nanmu42** [comment]
@rhiswell 请问镜像登记事宜有进展否？

**Comment by nanmu42** [comment]
Closed via https://github.com/nanmu42/CQUThesis#提问和支持 ，以及 #31 .
