### ISSUE TITLE
本科毕业论文格式的要求是目录部分每个chapter后面也要有点

### ISSUE THREAD

**Issue by xterat** [nanmu42/CQUThesis#30]

**Comment by xterat** [comment]
可以通过在cquthesis.sty文件的代码开发区后面加上这段代码解决
```
\usepackage{tocloft}
 
\renewcommand\cftchapdotsep{\cftdotsep}
\renewcommand\cftchapleader{\cftdotfill{\cftchapdotsep}}
```

**Comment by nanmu42** [comment]
@fengzipei ，你好，可以提供以下改变前后的截图吗？
另外，中文目录有类似要求吗？
谢谢你的反馈，在核对后我会进行更新。

**Comment by xterat** [comment]
改之后：![screen shot 2017-05-28 at 22 09 38](https://cloud.githubusercontent.com/assets/7146258/26529464/c7dddf38-43f2-11e7-8311-07cca71ea27b.png)
改之前：![screen shot 2017-05-28 at 22 11 15](https://cloud.githubusercontent.com/assets/7146258/26529465/c8400366-43f2-11e7-9d1d-d877b87d76f3.png)
要求来源：
![image](https://cloud.githubusercontent.com/assets/7146258/26529537/11743420-43f4-11e7-96bf-6b7933ee6957.png)

**Comment by nanmu42** [comment]
谢谢你，我会尽快修正这个问题。

**Comment by xterat** [comment]
嗯嗯，也谢谢你提供的模板^_^

**Comment by nanmu42** [comment]
已经修正，感谢支持：
https://github.com/nanmu42/CQUThesis/pull/31
您的名字已经录入：
https://github.com/nanmu42/CQUThesis/blob/master/CONTRIBUTORS.md
