### ISSUE TITLE
提供LyX支持

### ISSUE THREAD

**Issue by hongyuanjia** [nanmu42/CQUThesis#34]
首先感谢提供如此规范强大的重大毕业论文LaTeX模板。

[LyX](http://www.lyx.org/)可以理解为一个基于LaTeX的前端“所见即所想”的GUI，使用起来特别方便。目前LyX支持CTeX里的所有documentclass，由R语言大神[谢益辉](https://yihui.name/cn/2011/05/write-chinese-in-lyx/)完成。

想请问，目前团队是否有提供LyX的重大模板的计划？感谢！

**Comment by nanmu42** [comment]
hongyuanjia，你好：

欢迎使用CQUThesis！
我没有过使用Lyx的经验，难以完成这方面的适配开发。但是我认为支持Lyx确实是个好主意。
如果你有相关经验，欢迎提供开发思路或者Pull Request。
欢迎加入重庆大学TeX用户组QQ群进行讨论，地址在README.md中。
谢谢。

**Comment by nanmu42** [comment]
目前社区力量还比较有限，无法做好Lyx模板的长期支持和维护。
这个问题恐怕得留到以后再解决了。
感谢你的提议。
