### ISSUE TITLE
目录页的标题（「目录」）与目录项间距如何调整？

### ISSUE THREAD

**Issue by rhiswell** [nanmu42/CQUThesis#35]

**Comment by nanmu42** [comment]
rhiswell，你好：
CQUThesis使用`tocloft`宏包对目录进行定制。
请参阅[用户手册](https://github.com/nanmu42/CQUThesis/raw/master/cquthesis.pdf)的以下部分：
1. 第19页（L22）
1. 第46页（L985-L1002）

**Comment by nanmu42** [comment]
另外建议参阅`tocloft`宏包手册：
```
texdoc tocloft
```

**Comment by rhiswell** [comment]
谢谢建议，我已顺利强行解决（07 年学校模版要求目录、章节名前后空一行）。

```latex
% cquthesis.cls
\setlength{\cftbeforetoctitleskip}{20bp}
\setlength{\cftaftertoctitleskip}{12bp}
```

**Comment by nanmu42** [comment]
间距应该是预留过的。

Zhiqiang He <notifications@github.com>于2017年6月12日周一 下午5:23写道：
