### ISSUE TITLE
某些中文字体无法显示

### ISSUE THREAD

**Issue by panovr** [nanmu42/CQUThesis#36]
在使用过程中，发现某些中文字体无法显示，例如“鳾”，“鹀”，“鹟”。有没有什么解决办法？能不能把模板中的中文字体换为“思源黑体”？

**Comment by nanmu42** [comment]
panovr, 你好：

CQUThesis的中文支持基于CTeX宏包，我想你可以从这方面着手。
估计你是在Linux系列的系统上进行编译的，该情况下CTeX宏包默认调用Fandol字库，字符集会比较有限。

你可以使用
```
texdoc ctex
```
命令打开CTeX宏包文档，参考第4.3节部分的内容自定义使用的字符集。
建议使用XeLaTeX进行编译。
使用`fc-list`命令可以查看目前系统上可以被TeX访问到的字体。

祝你好运！
在问题解决后，欢迎分享你的方法。

**Comment by panovr** [comment]
感谢回复。对了，如果在Windows操作系统上面使用CQUThesis，是不是推荐使用TexLive？

**Comment by nanmu42** [comment]
最新版的MikTeX和TeX Live都可以，我比较喜欢前者。

**Comment by nanmu42** [comment]
@panovr 字体定制方面有进展吗？

**Comment by panovr** [comment]
@nanmu42 暂时还没有解决。我使用的是Ubuntu 16.04，发现确实CTeX宏包默认使用的是Fandol字库。我正在看CTeX的文档，如果有进展会及时回复。

**Comment by nanmu42** [comment]
祝好运，期待你的分享。

Yili Zhao <notifications@github.com> 於 2017年7月5日 週三 下午10:50 寫道：

**Comment by nanmu42** [comment]
closed via inactivity over 20 days.
If further help is needed, feel free to reopen this issue.

regards

**Comment by panovr** [comment]
经过验证，确实是Ubuntu下面CTex宏包使用字体的问题。在Windows下面使用TexLive则字体显示正常。

**Comment by nanmu42** [comment]
感谢反馈。
看来`Fandol`字库的缺字问题还是比较严重的。
