### ISSUE TITLE
cquthesis.cls 260行报错

### ISSUE THREAD

**Issue by Coder-Yu** [nanmu42/CQUThesis#39]
Win下Miktex环境，报
！Undefined control sequence.
1.260 \ctexset
                       {%
?
请问如何解决？？我同学Mac下编译无错。

**Comment by nanmu42** [comment]
使用MiKTeX的宏包管理器将CTeX宏包更新到最新版本，再做尝试。

**Comment by Coder-Yu** [comment]
刚查了下，好像ctexset 2.2前的宏包不支持，我更新试试看，谢谢了

**Comment by nanmu42** [comment]
如果仍然遇到问题，欢迎reopen后反馈。
