### ISSUE TITLE
CQUThesis的意义是什么？

### ISSUE THREAD

**Issue by Coder-Yu** [nanmu42/CQUThesis#41]
这模板没有参考最新标准编写么？？

**Comment by Coder-Yu** [comment]
"好多地方都不对，没法说得清楚。你可以找一个你们同学已经审核通过的格式来参照着排"

这是教务老师的原话。。


我对比了一下规范模板，然后点进去cls文件看了下，页边距什么的都不一样。你们这是在认真维护吗？？？不对的东西放出来岂不是坑人？

**Comment by nanmu42** [comment]
# tl; dr

@Coder-Yu ，模板给你带来了麻烦，对此我深表歉意，但也仅限于此了（请参阅[用户协议](https://github.com/nanmu42/CQUThesis#%E7%94%A8%E6%88%B7%E5%8D%8F%E8%AE%AE)）。

# 给 Coder-Yu 的回复

抱歉，同学。

CQUThesis和[重庆大学TeX用户组](http://jq.qq.com/?_wv=1027&k=2HvYu95)马上就要两岁了，它们的年纪已经大到可以有自己的小故事了。

## 关于页边距

页边距其实并没有看起来那么简单，模板开发之初，我就意识到了一个问题—— MS Word 的页边距和 LaTeX 的有不小差别，更糟糕的是， MS Word 有很多版本，版本之间也存在差异（甚至，别忘了打印店的缩放比例）。

我读了很多遍学校的[论文写作规范](https://github.com/nanmu42/CQUThesis#%E8%AE%BA%E6%96%87%E5%86%99%E4%BD%9C%E8%A7%84%E8%8C%83)，和[CQUtug](https://github.com/CQUtug)的@BluesCas 商量了很久，最后，我做了取舍，打出了几份样稿，与前辈过审论文做比较，取页边距最相似的那些参数。

这便是为什么模板的页边距参数和规范中的不一样的原因——如果参数一样，论文的效果反而不一样。

## 难道MS Word就是排版标准吗？

很遗憾，看起来是的。

你应该知道，中国的LaTeX土壤并不肥沃，重庆大学亦然。

我们[做过一些努力](https://github.com/CQUtug/TeXProposal)，也得到过[一些成果](https://github.com/CQUtug)（比如学校现在有自己的CTAN镜像了， 见#28 ），但目前来看，这些还远远不够。

## 为什么CQUThesis不给出合规性保证？

你应当知道，选择了LaTeX而非Word，你其实是在困难和容易中选择了前者。

用LaTeX排版从来都不是一件简单的事情——缺少面对面的交流和辅导，中文文档稀缺，社区小，LaTeX本身的生态以及依赖管理也有问题。

进群的新人经常会问两个问题，我们会这么回答他们：

> “模板一定能通过审查吗？”

不会。你需要一个支持你使用LaTeX的导师（很多导师偏爱Word的“审阅”功能），以及最大化使用你自己的LaTeX技术。

> “我Word用着不顺手，学习LaTeX再使用模板，会更轻松吗？”

如果你熟悉其他编程语言，那么，可能是。

如果你并不熟悉，我们建议你学好Word。Word经过长足的发展，现在已经是一个设计合理，功能足够，使用方便，社群庞大的文字编辑软件，使用它，你能很好的完成论文排版工作。

## CQUThesis的意义在哪里？

这个问题的答案一直在变化。

一开始，CQUThesis只是为了满足我和@BluesCas 的毕业论文排版需求。

后来，别人开始对它产生兴趣，我们便建立了一个小小的[重庆大学TeX用户组](http://jq.qq.com/?_wv=1027&k=2HvYu95)。

现在，它是[社区的产物](https://github.com/nanmu42/CQUThesis/blob/master/CONTRIBUTORS.md)，我们无偿投入这些精力，是因为我们体验过缺少同伴和工具的寒夜，我们想为别人搭把手。

搭把手，但，不是更多。

我们还有自己的生活和事业，自己的快乐与烦恼，请你理解。

我们贡献开源，但不投身开源。

希望你能接受我们的理念。

## 接下来

接下来，你可以考虑加入我们的社区，像一年前**FIVE**提交他用CQUThesis排版的博士论文时一样，我们试着为你出一些主意，为你 _自助_ 度过难关出谋划策。

尤其欢迎你提交PR，解决CQUThesis的相关问题。

谢谢你的反馈。

**Comment by Coder-Yu** [comment]
我尊重你们的劳动成果，也认为重庆大学应该推广使用LaTex，但是连封面目录字体都对不上，我不禁怀疑你们工作的认真程度了。你们自发的做这些事情我很欣赏也赞同，我自己也是长期开源代码的人。但是做了就要做好吧，如果只是一点点问题，我也懂这是求全责备。可是问题太多这就不对了。希望你们好好照着规范模板至少把字体间距这样弄一致吧。

**Comment by nanmu42** [comment]
封面字体规范里没有规定的，我们也有通过先例，对于你的情况，就需要你按需调整了。

> 可是问题太多这就不对了。希望你们好好照着规范模板至少把字体间距这样弄一致吧。

欢迎提供列表。

**Comment by Coder-Yu** [comment]
![image](https://user-images.githubusercontent.com/6328763/38599851-9a3d7bc8-3d94-11e8-8855-d9d71dc9de68.png)
默认的是无衬线的字体

**Comment by nanmu42** [comment]
哈哈，你向后看，我记得这个示例文件还在图注那里折了一行。

我会注意这个问题的，谢谢反馈。

p.s. 图中的字体为衬线字体，[详见](https://zh.wikipedia.org/wiki/%E6%97%A0%E8%A1%AC%E7%BA%BF%E4%BD%93)。

**Comment by Coder-Yu** [comment]
https://wenku.baidu.com/view/20ad191e04a1b0717ed5dd27.html

你可以对照这个看下哪些地方有问题，我觉得有很多不同

我说的是LaTex的模板默认的是无衬线的，英文就是Arial

**Comment by nanmu42** [comment]
欢迎提交PR.

**Comment by Coder-Yu** [comment]
请问目录部分页码的大小怎么改，模板里面默认的偏大一号  还有怎么不让chapter对应的页码自动加粗？

**Comment by nanmu42** [comment]
pdf参考文档中有实现细节，建议从目录开始检索。
