### ISSUE TITLE
CQUThesis的意义是什么（后续）

### ISSUE THREAD

**Issue by Coder-Yu** [nanmu42/CQUThesis#43]
非常的多的格式对不上！一旦使用了这个模板，意味着你将花费超过Word数倍的时间来将格式改到同官方模板统一的标准。不要使用这个模板！！不要使用这个模板！！不要使用这个模板！！说三遍。
另外，我在此献上我的BS，跟模板不匹配的东西不要放出来推广好吗。奉劝维护人员负责任一点把模板改到同官方一致再发布，不然被坑的人如我是不会尊重你们的劳动成果的。

**Comment by nanmu42** [comment]
请配合 #41 阅读。

**Comment by BluesCas** [comment]
贴上 4 月 12 日 我在用户组里对这位同学的回复：
我们用户组其实从成立之初就是在坚持或者说秉承“一个自发形成的松散的兴趣群体”的理念，我们共用的努力方向始终是面向学校，向学校建议为毕业论文写作方式提供多元化的支持，为对 LaTeX 有浓厚兴趣或因为某些原因倾向于 LaTeX 写作的同学谋取空间和创造便利的解决方式。
用户组大事记上@nanmu42 同学写作并维护模版，前期用户组每周睡衣派对为大家提供大量学习资源和解决方案信息（群文件可下载），以及耗时数月由用户组核心成员联手为母校提供的《关于推荐重庆大学开展 LaTeX 课程并推广其运用的提议》，提议不久便迎来母校建立 CTAN 节点的反馈可算是成立仅一年半的用户组迈出不错的第一步。
然而，这所有的工作目的仅仅是帮助母校打开一扇开放的大门，我们所期待的推广是由学校官方进行的，普及关于 LaTeX 的知识可算是义务，但这义务绝不包含建议某同学使用 LaTeX 的意味，相反，我们在遇到犹豫不定或略显盲目或咨询态度的同学时，我们强烈建议的是在无十足把握时避免使用 LaTeX 撰写毕业论文，毕业论文内容之上，排版工具永远只是工具，正如毕业论文只有自己为自己负责一样，选择什么样的排版工具永远都是个人选择，个人行为。
我的毕业论文是使用 @nanmu42 当时的第一个 CQUThesis 的版本写的，那时还远没有现今的完善度，可以说最初的几个 issue 都是我提的，那时 @nanmu42 事务繁忙，不可能总有时间随时跟进 issue 进行代码更新；我那时甚至还不懂 cls 文件的语法，但大部分诸如行距、字号、粗体、页眉等等绝大部分的参数调节完全是可以通过简单的宏包命令调控的。我借来同学的 Word 版论文，和自己的 LaTeX 排版结果同时打印，各个细节逐一校对，然后宏包命令调试，也加入了自己的一些对美学的理解。整个调试其实并不耗时，因为即便是第一个版本的模版 @nanmu42 也是拿来长篇累牍的重庆大学论文写作规范一个字一个字地抠的，上乘的模版基础一点个性化调试，毕业答辩时五位评委我打印了五厚沓纸质论文一人一份，没有任何一个规范上的问题，论文全组第一推优，根本没遇到任何障碍。
我想说的是，使用 LaTeX 排版论文一定会比 Word 更加耗时，我相信我在排版上花的时间是其他同学的两倍以上，但时间换取了论文中的系统感带来的满足，换取了 LaTeX 运用上的实战积累，同时也冒着格式审查的风险。
我更想说的是，我们用户组成立的目的，我们共同努力的方向，是让你我这种欣赏 LaTeX 的设计思路或想要借 LaTeX 从编程思维上取得突破的同志同僚同学们冒更少格式审查的风险，所以我们一方面极力建议学校官方放宽制度，一方面劝导不充分了解 LaTeX 的同学不要因为好奇心或虚荣心而轻易试水，一方面尽力维护模版的可靠性来提供一个更上乘的供个人精细调试的模版基础。
我们的目的，确切地说现阶段的目的绝不是让懒于细看重庆大学格式审查规范的同学逃避排版的！仔细对照排版规范是每一个合格的毕业生必须的义务，是写进学校规章的成为一个合格的毕业生的前提，无论他是用 Word 还是用 LaTeX，都需要按照排版规范调试自己的论文。
正如我的导师常告诉我的 your phd is your phd，同样，your thesis is your thesis. 我们当然需要大家的共同努力来维护这个刚刚诞生不久的模版，我们渴求各方面更细节更深入的建议和要求，我们无比欢迎同好和同兴趣的同学们共同交流彼此提升，但连自己顺利毕业的命运也无法掌控在自己手中的人，不属于用户组，也不属于创新思维，不属于独立思考，不属于 IT 精神，更不属于重庆大学矢志培养的人才。
试问如果发展 LaTeX 带来的是同学们对排版规范的无视与轻视，那让学校如何推动，如何愿意推动论文写作的多元化进程？
