### ISSUE TITLE
siunitx 宏包配置的几个问题

### ISSUE THREAD

**Issue by zepinglee** [nanmu42/CQUThesis#44]
参考了一下贵校的 `siunitx` 宏包配置，顺便反馈两个问题：

1. `list-final-separator = {和},` 应该在“和”的前后加空格，这样更符合中西文混排的习惯；`list-pair-separator` 同样。

2. `range-phrase = {$ \sim $},` 这里的 `\sim` 的用法是错误的，应该使用 “～”（Unicode FF5E）。

**Comment by nanmu42** [comment]
感谢反馈。 :beers:

**Comment by nanmu42** [comment]
Closed via 0dbe8da.
