### ISSUE TITLE
==ubuntu上装完了 但是并不知道latex怎么用啊

### ISSUE THREAD

**Issue by QiuYilin** [nanmu42/CQUThesis#45]
从零开始的教程有吗 这个主题具体怎么用啊

**Comment by ilcpm** [comment]
> 从零开始的教程有吗 这个主题具体怎么用啊

建议你先学习一下LaTeX，这个是个LaTeX的模版，直接下载发布版本解压然后使用就可以了

**Comment by nanmu42** [comment]
如果之前没有编程经验，LaTeX的学习难度还是比较大的。

欢迎加入[重庆大学TeX用户组](http://jq.qq.com/?_wv=1027&k=2HvYu95)寻求答疑。
