### ISSUE TITLE
“makewin.bat” 安装报错

### ISSUE THREAD

**Issue by jimyug** [nanmu42/CQUThesis#46]
![image](https://user-images.githubusercontent.com/29953124/55787241-6f6f7a00-5ae8-11e9-8f91-9beea5e7d1f1.png)

如图所示，在 Win10 专业版 + TeX Live 2018（各软件包已更新为最新版）环境下运行 “makewin.bat” 会报错。已确定路径无中文，且已是管理员模式启动。

在 Mac OS 上使用是可以成功编译的，所以猜测可能是 Windows 环境的问题，但是具体问题在哪暂时没啥头绪，烦请开发组帮助，谢谢！

**Comment by nanmu42** [comment]
请先尝试使用宏包管理器将各个宏包更新到最新版，这可以解决大部分表征类似的问题。

Tip: Windows上推荐使用MikTeX发行版，能够自动安装更新宏包。

**Comment by nanmu42** [comment]
另外也考虑是缺宏包导致的。

建议使用MiKTeX，可以减轻不少这方面的负担。

**Comment by jimyug** [comment]
感谢回复！

改成 MiKTeX 之后编译通过了，应该是 TeX Live 没配置好的问题，谢谢！

**Comment by nanmu42** [comment]
客气了。
