### ISSUE TITLE
LaTeX生成的pdf查重问题

### ISSUE THREAD

**Issue by Chengyuan-Zhang** [nanmu42/CQUThesis#47]
你好，利用LaTeX生成的pdf文档在查重时仅能识别公式和英文字符，请问有什么解决方法吗？

**Comment by nanmu42** [comment]
从你的描述来看，似乎学校订购的查重服务对PDF的支持有限。

如果查重服务能够提交txt文件，考虑使用pandoc（全平台）或pdftotext（Linux, Mac, https://linux.die.net/man/1/pdftotext ）进行转换后提交。

如果仅支持提交doc文件，考虑尝试Pandoc或Acrobat（收费软件，不过似乎有试用期）。

如果可能，请和我分享你的后续情况。

**Comment by Chengyuan-Zhang** [comment]
谢谢！我最后采用pandoc转docx提交查重，查重之后再重新提交的pdf版作为终稿。
