### ISSUE TITLE
cquthesis.cls样式文件编译出错(line 339,340)

### ISSUE THREAD

**Issue by JoshuaWu1997** [nanmu42/CQUThesis#51]
xelatex和latexmk编译都出现fatal error：
Package caption: `bi-first' undefined in families `cap
tion'.
Package caption: `bi-second' undefined in families `ca
ption'.

cquthesis.cls: line 339-348
```tex
\captionsetup[bi-first]{bi-first}
\captionsetup[bi-second]{bi-second}
\DeclareCaptionOption{bi-first}[]{%
\def\tablename{\shorttablename}
\def\figurename{\shortfigurename}
}%bi-first
\DeclareCaptionOption{bi-second}[]{%
\def\tablename{\shorttablenameEN}
\def\figurename{\shortfigurenameEN}
}%bi-second
```

尝试交换DeclareCaptionOption和captionsetup语块位置，error解决。

**Comment by nanmu42** [comment]
抱歉，我没法重现这个问题。目前的代码看起来是正常工作的。

下次遇到这个问题，也许你可以运行下`make cleanall`，有时候异常状态的中间文件（`*.aux`等）会导致错误。
