### ISSUE TITLE
Support for physics symbols and algorithmic diagram

### ISSUE THREAD

**Issue by EigenSolver** [nanmu42/CQUThesis#56]
Suggest add more CTAN packages in template, for complex physics symbols, like \partial derivative  or Dirac symbol.

And some packages for computer science diagrams...maybe algrithm2e or something like that

**Comment by EigenSolver** [comment]
think this should be implemented in cquthesis.sty.... 

maybe it's not general enough to add the packages to global environment

**Comment by nanmu42** [comment]
I see your PR #58 has resolved this, thank you very much.
