### ISSUE TITLE
请问使用时是直接对main.tex 进行编写吗？我在WinEdt中，采用LuaLatex编译没有错误，但是不能生成PDF。

### ISSUE THREAD

**Issue by Alisatjg** [nanmu42/CQUThesis#61]
使用手册里面写的  makewin doc，也有挺多错误，目前修改到如下情况：
`Package thumbpdf Warning: Missing driver name.

)) (C:\Users\TJG\Desktop\CQUThesis-master\ctex.sty
(d:\CTEX\MiKTeX\tex\latex\l3kernel\expl3.sty
(d:\CTEX\MiKTeX\tex\latex\l3kernel\l3names.sty
(d:\CTEX\MiKTeX\tex\latex\l3kernel\l3bootstrap.sty))
(d:\CTEX\MiKTeX\tex\latex\misc\etex.sty)
(d:\CTEX\MiKTeX\tex\latex\graphics\color.sty
(d:\CTEX\MiKTeX\tex\latex\00miktex\color.cfg)
(d:\CTEX\MiKTeX\tex\xelatex\xetex-def\xetex.def))
(d:\CTEX\MiKTeX\tex\latex\graphics\graphics.sty
(d:\CTEX\MiKTeX\tex\latex\graphics\trig.sty)
(d:\CTEX\MiKTeX\tex\latex\00miktex\graphics.cfg))
(d:\CTEX\MiKTeX\tex\latex\l3kernel\l3basics.sty)
(d:\CTEX\MiKTeX\tex\latex\l3kernel\l3expan.sty)
(d:\CTEX\MiKTeX\tex\latex\l3kernel\l3tl.sty)
(d:\CTEX\MiKTeX\tex\latex\l3kernel\l3seq.sty)
(d:\CTEX\MiKTeX\tex\latex\l3kernel\l3int.sty)
(d:\CTEX\MiKTeX\tex\latex\l3kernel\l3quark.sty)
(d:\CTEX\MiKTeX\tex\latex\l3kernel\l3prg.sty)
(d:\CTEX\MiKTeX\tex\latex\l3kernel\l3clist.sty)
(d:\CTEX\MiKTeX\tex\latex\l3kernel\l3token.sty)
(d:\CTEX\MiKTeX\tex\latex\l3kernel\l3prop.sty)
(d:\CTEX\MiKTeX\tex\latex\l3kernel\l3msg.sty)
(d:\CTEX\MiKTeX\tex\latex\l3kernel\l3file.sty)
(d:\CTEX\MiKTeX\tex\latex\l3kernel\l3skip.sty)
(d:\CTEX\MiKTeX\tex\latex\l3kernel\l3keys.sty)
(d:\CTEX\MiKTeX\tex\latex\l3kernel\l3fp.sty)
(d:\CTEX\MiKTeX\tex\latex\l3kernel\l3box.sty)
(d:\CTEX\MiKTeX\tex\latex\l3kernel\l3coffins.sty)
(d:\CTEX\MiKTeX\tex\latex\l3kernel\l3color.sty)
(d:\CTEX\MiKTeX\tex\latex\l3kernel\l3luatex.sty)))
Runaway argument?
01:15:24\relax  \ProvidesExplPackage {\ExplFileName } {\ExplFileDate \ETC.
! File ended while scanning use of \GetIdInfoAuxSVN.
<inserted text>
                \par
l.26 \RequirePackage
                    [
?`
不知道应该怎么使用模板，抱歉，是否可以详细说明一下？感谢

**Comment by nanmu42** [comment]
你好，

请阅读用户文档后使用XeLaTeX编译，注意确保安装的TeX发行版为最新的MiKTeX或者TeX Live（不推荐）。

更多问题，请加入重庆大学TeX用户组QQ群咨询：198990284.

新年好。
