### ISSUE TITLE
想请教下如何修改 参考文献环境，让序号左对齐？

### ISSUE THREAD

**Issue by gkeyes** [nanmu42/CQUThesis#62]
发现范文中的序号是右对齐，怎么让他左对齐呢？谢谢

**Comment by nanmu42** [comment]
你好，我已经毕业多年，现在基本上不使用LaTeX了。

请加入重庆大学TeX用户组QQ群进行讨论：198990284.

谢谢。

gkeyes <notifications@github.com> 於 2021年3月4日 週四 下午2:37 寫道：
