### ISSUE TITLE
如何修改bst文件，使参考文献中的学位论文引用中去掉[出版地不祥]及英文文献的DOI链接？

### ISSUE THREAD

**Issue by Cheng1874** [nanmu42/CQUThesis#63]
![image](https://user-images.githubusercontent.com/58622700/119313487-3255aa00-bca6-11eb-8749-7af06c4d1578.png)
![image](https://user-images.githubusercontent.com/58622700/119313520-3bdf1200-bca6-11eb-88cc-dd28e68c7e01.png)

**Comment by ilcpm** [comment]
给你指条路，去 https://wenda.latexstudio.net 注册个账号好好提问

记得先看看如何提问 https://wenda.latexstudio.net/note/view/1.html

**Comment by nanmu42** [comment]
这个我也帮不上忙。请到上游仓库进行提问：https://github.com/CTeX-org/gbt7714-bibtex-style
