### ISSUE TITLE
关于 GitHub 的 template 仓库类型

### ISSUE THREAD

**Issue by Hagb** [nanmu42/CQUThesis#65]
GitHub 的 template 仓库是指该仓库作为其他仓库生成的模版，而和 LaTeX 模版并没有直接联系（见 https://docs.github.com/articles/creating-a-repository-from-a-template/ ）。
该仓库似乎并不是这种 template 类型的仓库，建议改回普通的仓库类型。

**Comment by nanmu42** [comment]
感谢你的建议。

这个仓库的确可以作为论文编写的模板，用户在点击use template后生成自己的仓库，然后基于新仓库编写（“开发”）自己的论文。
