### ISSUE TITLE
文献引用的格式

### ISSUE THREAD

**Issue by mark-golden** [nanmu42/CQUThesis#69]
现在的参考文献的格式是根据数字[1] [2]...的排列格式，想问以下如果想按照首字母的顺序来进行排列，应该怎么弄呢？

**Comment by nanmu42** [comment]
啊，已经过去太久了，我忘了……

如果[文档](https://github.com/nanmu42/CQUThesis/raw/master/cquthesis.pdf)不能解决你的问题，你可以到用户QQ群里问问：198990284
