### ISSUE TITLE
Writing in English only?

### ISSUE THREAD

**Issue by aljbri** [nanmu42/CQUThesis#72]
Is there a way to make the figures and tables captions in English while using "bilinguallist=off", also the titles of :

- Table of Contents 
- List of Equations
- List of Figures
- List of Tables
- References 

in other words can the template has a configuration for writing in English only.

**Comment by nanmu42** [comment]
Unfortunately There's no direct way to use the English version. You may need to tweak the template by yourself.

**Comment by aljbri** [comment]
> Unfortunately There's no direct way to use the English version. You may need to tweak the template by yourself.

Thank you so much

**Comment by nanmu42** [comment]
You are very welcome.
