### ISSUE TITLE
A Chinese Character 堃

### ISSUE THREAD

**Issue by aljbri** [nanmu42/CQUThesis#73]
Dear LI,

I am trying to write the Chinese character '堃' but unfortunately it does not appear correctly. Instead, I get a different symbol � it looks like a square with the character F inside.

**Comment by note286** [comment]
默认应该是`fandol`字体，更换其他中文字体就好了。

**Comment by nanmu42** [comment]
Fandol font has really limited character coverage.

Try using other Chinese font instead.

**Comment by aljbri** [comment]
> 默认应该是`fandol`字体，更换其他中文字体就好了。

请问，我怎么换中文字体？
我可以用什么命令，具体在哪里？

**Comment by note286** [comment]
最顶部加`\PassOptionsToClass{fontset=windows}{ctexbook}`，`\documentclass`上面。

**Comment by aljbri** [comment]
> 最顶部加`\PassOptionsToClass{fontset=windows}{ctexbook}`，`\documentclass`上面。



发生以下错误:
`
Package fontspec Error: The font "...." cannot be found
`
对于以下字体:

1. SimSun
2. SimHei
3. KaiTi
4. Microsoft YaHei
5. Microsoft YaHei Bold

**Comment by note286** [comment]
你是什么操作系统？

**Comment by aljbri** [comment]
overleaf网站，可能是 Linux.
该错误仅在我执行命令“PassOptionsToClass”后发生

**Comment by note286** [comment]
当然，Overleaf没什么字体，只有思源和fandol，你要吗上传字体，要么本机编译。

**Comment by aljbri** [comment]
> 当然，Overleaf没什么字体，只有思源和fandol，你要吗上传字体，要么本机编译。

在Overleaf上我怎么能做其中的任何一个

**Comment by note286** [comment]
你试试`fontset=ubuntu`，或者直接设置为`none`，手动用xeCJK配置字体，不走ctex那一套。

**Comment by aljbri** [comment]
> 你试试`fontset=ubuntu`，或者直接设置为`none`，手动用xeCJK配置字体，不走ctex那一套。

多谢，`fontset=ubuntu`  解决了问题，但字体大小有点细
