### ISSUE TITLE
dtx-style 没有，无法编译使用手册

### ISSUE THREAD

**Issue by texbowman** [nanmu42/CQUThesis#8]
按照您 README-EN.md 文件的说明，用下面的命令，想编译出使用手册：

```
xelatex cquthesis.dtx
makeindex -s gind.ist -o cquthesis.ind cquthesis.idx
makeindex -s gglo.ist -o cquthesis.gls cquthesis.glo
xelatex cquthesis.dtx
xelatex cquthesis.dtx
```

但一上来就报没有 dtx-style.sty 的错误：

```
! LaTeX Error: File `dtx-style.sty' not found.
```

请问这是您写 ltxdoc 文档时，自己写的一个文件吗？把你写手册用到的宏包和命令都写到那里面去了？

顺便说一句，您的海报做得实在是太牛了！那个细节， The TeX Book 的封面（狮子手里拿的）上有您的模板，超赞！

**Comment by nanmu42** [comment]
张，你好！
欢迎使用CQUThesis！:)

模板的dtx-style文件打包到了cquthesis.dtx当中，你可以在解压后的目录运行：

latex cquthesis.ins

将dtx-style.sty文件以及模板的cls和cfg文件提取出来。

之后就可以按你既有的方法对用户手册进行编译了。

另外，用户手册可以在项目的Github主页上直接下载，在“获取CQUThese”部分有链接。

对了，我们还有示例文档哟，联系你也参考下，使用XeLaTeX编译main.tex就好。

感谢你的反馈。
祝你好运，期待你的好消息！

李振楠

p.s 谢谢夸奖，小狮子是Ctan lion，LaTeX的吉祥物，功劳我不能全拿～:p

mingdi_zhang notifications@github.com 於 2016年5月20日週五 17:38 寫道：

**Comment by nanmu42** [comment]
很高兴能帮助到你。:)
祝你愉快！

mingdi_zhang notifications@github.com 於 2016年5月20日週五 21:05 寫道：
